// ui/src/App.tsx
import { useEffect, lazy, Suspense } from 'react'
import { Toaster, toast } from 'sonner'
import { store } from './lib/store'
import Toolbar from './components/Toolbar'
import NodePalette from './components/NodePalette'
import FlowCanvas from './components/FlowCanvas'
import PropertyPanel from './components/PropertyPanel'
import { useStore } from './lib/useStore'

const CredentialsPage = lazy(() => import('./components/CredentialsPage'))
const HistoryPage = lazy(() => import('./components/HistoryPage'))

export default function App() {
  const page = useStore(s => s.currentPage)

  useEffect(() => {
    store.loadSample()
    store.fetchSkills()
    store.fetchCredentials()
  }, [])

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const success = params.get('oauth_success')
    const error = params.get('oauth_error')
    if (success) {
      toast.success(`OAuth credential created (${success})`)
      store.fetchCredentials()
      store.navigateTo('credentials')
      window.history.replaceState({}, '', '/')
    } else if (error) {
      toast.error(`OAuth failed: ${error}`)
      window.history.replaceState({}, '', '/')
    }
  }, [])

  if (page === 'credentials') return <Suspense fallback={<div className="h-screen flex items-center justify-center text-muted-foreground">Loading...</div>}><CredentialsPage /></Suspense>
  if (page === 'history') return <Suspense fallback={<div className="h-screen flex items-center justify-center text-muted-foreground">Loading...</div>}><HistoryPage /></Suspense>

  return (
    <div className="h-screen flex flex-col bg-background text-foreground">
      <Toaster richColors position="top-right" />
      <Toolbar />
      <div className="flex flex-1 overflow-hidden">
        <NodePalette />
        <FlowCanvas />
        <PropertyPanel />
      </div>
    </div>
  )
}

// ui/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import CredentialsPage from './lib/CredentialsPage.svelte'
  import HistoryPage from './lib/HistoryPage.svelte'
  import Toolbar from './lib/Toolbar.svelte'
  import NodePalette from './lib/NodePalette.svelte'
  import FlowCanvas from './lib/FlowCanvas.svelte'
  import PropertyPanel from './lib/PropertyPanel.svelte'
  import { getStore } from './lib/store.svelte.js'
  import Toast from './lib/Toast.svelte'

  const store = getStore()
  let toastMessage = $state('')
  let toastType = $state<'success' | 'error'>('success')

  $effect(() => { store.loadSample(); store.fetchSkills(); store.fetchCredentials() })

  $effect(() => {
    if (store.oauthMessage) {
      toastType = store.oauthType
      toastMessage = store.oauthMessage
      store.oauthMessage = ''
    }
  })

  onMount(() => {
    const params = new URLSearchParams(window.location.search)
    const success = params.get('oauth_success')
    const error = params.get('oauth_error')
    if (success) {
      toastType = 'success'
      toastMessage = `OAuth credential created (${success})`
      store.fetchCredentials()
      store.navigateTo('credentials')
      history.replaceState({}, '', '/')
    } else if (error) {
      toastType = 'error'
      toastMessage = `OAuth failed: ${error}`
      history.replaceState({}, '', '/')
    }
  })
</script>

{#if toastMessage}
  <Toast {toastType} message={toastMessage} onclose={() => toastMessage = ''} />
{/if}

{#if store.currentPage === 'credentials'}
  <CredentialsPage />
{:else if store.currentPage === 'history'}
  <HistoryPage />
{:else}
  <div class="h-screen flex flex-col bg-[#0f0f23] text-[#e0e0e0]">
    <Toolbar />
    <div class="flex flex-1 overflow-hidden">
      <NodePalette />
      <FlowCanvas />
      <PropertyPanel />
    </div>
  </div>
{/if}
