// ui/src/components/NodePalette.tsx
import { Button } from '@/components/ui/button'
import { CATEGORIES } from '@/lib/types'
import { store } from '@/lib/store'
import { useStore } from '@/lib/useStore'

function nodeLabel(type: string): string {
  const m = store.skillsMap[type]
  if (m?.name) return m.name
  return type.charAt(0).toUpperCase() + type.slice(1).replace(/-/g, ' ')
}

export default function NodePalette() {
  const skillsMap = useStore(s => s.skillsMap)

  function addToCanvas(type: string) {
    store.addNode(type, { x: 200 + Math.random() * 100, y: 150 + Math.random() * 100 })
  }

  function nodeDesc(type: string): string | undefined {
    return skillsMap[type]?.description
  }

  return (
    <aside className="w-40 border-r bg-card p-2 overflow-y-auto flex flex-col gap-1">
      <h3 className="text-xs text-primary uppercase tracking-wider font-semibold mb-2">Nodes</h3>
      {CATEGORIES.map(cat => (
        <div key={cat.name}>
          <h4 className="text-[10px] text-muted-foreground uppercase mt-2 mb-1 tracking-wider">{cat.name}</h4>
          {cat.nodes.map(type => (
            <Button
              key={type}
              variant="outline"
              size="xs"
              title={nodeDesc(type)}
              className="w-full justify-start text-xs font-mono text-muted-foreground mb-0.5"
              onClick={() => addToCanvas(type)}
            >
              {nodeLabel(type)}
            </Button>
          ))}
        </div>
      ))}
    </aside>
  )
}

// ui/src/lib/NodePalette.svelte
<script lang="ts">
  import { CATEGORIES } from './types'
  import { getStore } from './store.svelte.js'

  const store = getStore()

  function addToCanvas(type: string) {
    store.addNode(type, { x: 200 + Math.random() * 100, y: 150 + Math.random() * 100 })
  }
</script>

<aside class="w-40 bg-[#16162a] border-r border-[#333] p-2 overflow-y-auto flex flex-col gap-1">
  <h3 class="text-xs text-[#7c3aed] uppercase tracking-wider mb-2">Nodes</h3>
  {#each CATEGORIES as cat}
    <h4 class="text-[10px] text-[#888] uppercase mt-2 mb-1">{cat.name}</h4>
    {#each cat.nodes as type}
      <button
        class="px-2 py-1 border border-[#333] rounded bg-[#1e1e36] text-xs text-[#ccc] text-left font-mono cursor-pointer hover:border-[#7c3aed] hover:bg-[#2e2e4e]"
        onclick={() => addToCanvas(type)}
      >
        na-{type}
      </button>
    {/each}
  {/each}
</aside>
